Feature be signup
twosome0710/twiger pull request #14
Opened 2021-07-31 05:34 UTC by Jungjihyuk

## 작업 내용

- [x] 회원가입 API refactoring 
    - API test후 경로 설정 변경 
    - 회원 가입성공시 id및 성공 메시지 응답하도록 변경 
    - 회원 가입시 유효하지 않은 메일 및 중복되는 메일인 경우 에러 메시지를 응답 하도록 변경 
- [x] MongoDB Driver code refactoring 
    - secrets.json 파일에 Full driver code 추가

2021-07-31 07:04 UTC, kkole3897 requested changes
수고하셨습니다. 몇몇 부분 리뷰 드렸으니 확인 부탁드립니다.

2021-07-31 07:04 UTC, kkole3897 commented on client/.next/build-manifest.json
> +{
next.js에서 vue로 변경해서 `client/.next/` 디렉토리는 모두 삭제해도 됩니다

2021-07-31 07:04 UTC, kkole3897 commented on server/users/views.py
> +        return Response({"pid": str(pid), "messge": "Sign up success"}, status=status.HTTP_201_CREATED)
messge 오타 수정 부탁드립니다.
```suggestion
        return Response({"pid": str(pid), "message": "Sign up success"}, status=status.HTTP_201_CREATED)
```

2021-07-31 07:04 UTC, kkole3897 commented on server/users/views.py
> +        return Response({"message": "유효한 이메일 주소를 입력하시오."}, status=status.HTTP_400_BAD_REQUEST)
name이나 password 길이로도 is_valid() 통과하지 못하는 상황도 있을 것 같은데 혹시 해당 케이스도 존재한다면 메시지로 이메일 형식만 알리는 건 다소 부적절해보입니다.

\+ 마지막 줄 개행 부탁드립니다.

2021-07-31 07:04 UTC, kkole3897 commented on server/users/views.py
> +        pid = list(collection.find())[::-1][0]['_id']
`collection.find()`로 다시 새로 추가된 document를 찾아서 _id를 `pid`에 할당하는 것보다 `insert_one()`으로 반환되는 객체의 `inserted_id`를 `pid`에 직접 할당해 주는 방식이 더욱 효율적일 것 같습니다.

https://pymongo.readthedocs.io/en/stable/tutorial.html?highlight=insert_one#inserting-a-document

2021-07-31 07:04 UTC, kkole3897 commented on server/users/views.py
> +conn = MongoClient(get_key("Driver_Code"), tlsCAFile=certifi.where())
tlsCAFile 옵션은 인증서 따로 발급받을 필요 없이 사용가능한 옵션인가요? 아니면 따로 해줘야할 작업이 있을까요?

\+ Driver_Code 값 공유 부탁드립니다.

2021-07-31 07:04 UTC, kkole3897 commented on .gitignore
> +secrets.json
`server/. gitignore`에서 `json/secretes.json`이 동일한 역할을 하는 것 같은데 확인 부탁드립니다.

2021-07-31 07:12 UTC, kkole3897 commented
`config/__pycache__/` 디렉토리에 있는 파일들은 매번 컴파일해서 생성되는 것들인데 .gitignore로 제외해도 되지 않을까요?

2021-08-02 04:19 UTC, Jungjihyuk commented on client/.next/build-manifest.json
> +{
넵 알겠습니다

2021-08-02 04:20 UTC, Jungjihyuk commented on server/users/views.py
> +        return Response({"message": "유효한 이메일 주소를 입력하시오."}, status=status.HTTP_400_BAD_REQUEST)
오호 그건 미처 생각 못했군요

2021-08-02 04:20 UTC, Jungjihyuk commented on server/users/views.py
> +        pid = list(collection.find())[::-1][0]['_id']
오호 굳굳

2021-08-02 05:46 UTC, Jungjihyuk commented
> `config/__pycache__/` 디렉토리에 있는 파일들은 매번 컴파일해서 생성되는 것들인데 .gitignore로 제외해도 되지 않을까요?

<img width="175" alt="image" src="https://user-images.githubusercontent.com/33630505/127810138-9f88547d-dd07-476c-9bdd-9a41484446a7.png">

여기 추가 되어 있는데 왜 숨김처리가 안되는걸까요..ㅠ

2021-08-07 10:51 UTC, kkole3897 commented
커밋 로그 확인해보니까 .gitignore에 추가되기 전에 이미 안 올라가야했던 파일들이 올라가 있어서 문제가 발생한 것 같습니다.

2021-08-15 09:52 UTC, kkole3897 approved these changes
수고하셨습니다 👍

2021-08-15 09:54 UTC, merged